name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверить код репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить OCaml и Opam
      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: '5.1.0' # Укажите нужную версию OCaml
          opam-repository: 'default'

      # Шаг 3: Установить зависимости через Opam
      - name: Install dependencies
        run: |
          eval $(opam env)
          opam install dune alcotest --yes

      # Шаг 4: Скомпилировать проект
      - name: Build the project
        run: |
          eval $(opam env)
          dune build

      # Шаг 5: Запустить тесты
      - name: Run tests
        run: |
          eval $(opam env)
          dune runtest
