name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверить код репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить OCaml и Opam
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      # Шаг 3: Установить зависимости через Opam
      - name: Install dependencies
        run: |
          eval $(opam env)
          opam install dune alcotest --yes

      # Шаг 4: Скомпилировать проект
      - name: Build the project
        run: |
          eval $(opam env)
          dune build

      - name: Compile and run tests
        run: |
          eval $(opam env)
          # Компиляция тестов
          ocamlfind ocamlc -o test -package alcotest -linkpkg prefix_tree_bag.ml
          # Запуск тестов
          ./test
