name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: '4.14.0'  # Можно заменить на нужную версию OCaml

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y opam
        opam init --auto-setup
        opam switch create 4.14.0  # Замените на вашу версию OCaml
        eval $(opam env)
        opam install alcotest qcheck qcheck-alcotest

    - name: Build and test
      run: |
        eval $(opam env)
        dune build
        dune runtest  # Запускает тесты, если они настроены через dune

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest --verbose
