name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: '4.14.0'  # Используйте ocaml-compiler вместо ocaml-version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y opam
        opam init --auto-setup
        opam switch create . --deps-only  # Создаёт switch и устанавливает зависимости из .opam файлов
        eval $(opam env)
        opam install alcotest qcheck qcheck-alcotest

    - name: Build and test
      run: |
        eval $(opam env)
        dune build
        dune runtest  # Запускает тесты, если они настроены через dune

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest --verbose
